package Hibernate;
// Generated 06.12.2016 22:32:35 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * Activity generated by hbm2java
 */
public class Activity  implements java.io.Serializable {


     private Integer activityId;
     private Category category;
     private String activityName;
     private String activityDescription;
     private Timestamp activityStartTime;
     private Timestamp activityEndTime;

    public Activity() {
    }

    public Activity(Category category, String activityName, String activityDescription, Timestamp activityStartTime, Timestamp activityEndTime) {
       this.category = category;
       this.activityName = activityName;
       this.activityDescription = activityDescription;
       this.activityStartTime = activityStartTime;
       this.activityEndTime = activityEndTime;
    }
   
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getActivityName() {
        return this.activityName;
    }
    
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }
    public String getActivityDescription() {
        return this.activityDescription;
    }
    
    public void setActivityDescription(String activityDescription) {
        this.activityDescription = activityDescription;
    }
    public Timestamp getActivityStartTime() {
        return this.activityStartTime;
    }
    
    public void setActivityStartTime(Timestamp activityStartTime) {
        this.activityStartTime = activityStartTime;
    }
    public Timestamp getActivityEndTime() {
        return this.activityEndTime;
    }
    
    public void setActivityEndTime(Timestamp activityEndTime) {
        this.activityEndTime = activityEndTime;
    }




}


